name: Sync GitLab Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-gitlab-activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitLab Contributions and Generate Monthly Heatmap
        run: |
          echo "## My GitLab Activity 🚀" > gitlab_activity.md
          echo "" >> gitlab_activity.md
          
          # Fetch GitLab events and count contributions by month
          curl -s --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}" \
          "https://zivgitlab.uni-muenster.de/api/v4/users/fzhang/events" \
          | jq -r 'map(.created_at | split("T")[0]) | "\(.[0:7])") | group_by(.) | map({(.[0]): length}) | add' \
          > gitlab_contributions.json

          # Generate a Markdown table
          echo "| Month      | Contributions |" >> gitlab_activity.md
          echo "|------------|--------------|" >> gitlab_activity.md
          jq -r 'to_entries | sort_by(.key) | .[] | "| \(.key) | \(.value) |"' gitlab_contributions.json >> gitlab_activity.md
          
          echo -e "\n_Last updated: $(date)_\n" >> gitlab_activity.md
          mv gitlab_activity.md README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔄 Update GitLab activity $(date)" || echo "No changes to commit"
          git push
